Repository PepperBot-co/pepperbot, pull requests merged in 2023-05, with the labels that each got.

#1 Docs: Fix Broken URLs Across Documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#4 [PB-3] Daisy UI Setup and Base Components Implementation
  .eslintrc.cjs
  .gitignore
  package.json
  pnpm-lock.yaml
  public/favicon.ico
  src/assets/README.md
  src/components/card/index.tsx
  src/components/chat/index.tsx
  src/components/flow-builder/edge-types/index.ts
  src/components/flow-builder/edge-types/placeholder-edge.tsx
  src/components/flow-builder/edge-types/workflow-edge.tsx
  src/components/flow-builder/hooks/useEdgeClick.ts
  src/components/flow-builder/hooks/useLayout.ts
  src/components/flow-builder/hooks/useNodeClick.ts
  src/components/flow-builder/hooks/usePlaceholderClick.ts
  src/components/flow-builder/horizontal.tsx
  src/components/flow-builder/index.tsx
  src/components/flow-builder/node-types/index.ts
  src/components/flow-builder/node-types/placeholder-node.tsx
  src/components/flow-builder/node-types/workflow-node.tsx
  src/components/flow-builder/utils.tsx
  src/components/head-meta/head-meta.types.ts
  src/components/head-meta/index.tsx
  src/components/header/index.tsx
  src/components/icons/archive.tsx
  src/components/icons/delete.tsx
  src/components/icons/index.ts
  src/components/icons/user-plus.tsx
  src/components/layout/two-column.tsx
  src/constants/README.md
  src/hooks/README.md
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/trpc/[trpc].ts
  src/pages/flows/[flow].tsx
  src/pages/index.tsx
  src/server/api/root.ts
  src/server/api/routers/example.ts
  src/server/api/trpc.ts
  src/server/auth.ts
  src/server/db.ts
  src/styles/globals.css
  src/types/README.md
  src/types/index.ts
  src/utils/api.ts
  tailwind.config.ts
  tsconfig.json
Labels: documentation, feature

#11 [PB-6][Chat] Build chat component
  .env.example
  src/components/base-input/base-input.types.ts
  src/components/base-input/index.tsx
  src/components/chat-input/chat-input.types.ts
  src/components/chat-input/index.tsx
  src/components/chat/chat.types.ts
  src/components/chat/index.tsx
  src/components/icons/index.ts
  src/components/icons/reset-chat.tsx
  src/components/icons/send-arrow.tsx
Labels: feature

#14 [PB-13][Husky] Setup Husky
  .eslintrc.cjs
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/components/card/index.tsx
  src/components/chat-input/index.tsx
  src/components/chat/index.tsx
  src/components/checkbox-group/checkbox-group.types.ts
  src/components/checkbox-group/index.tsx
  src/components/flow-builder/edge-types/workflow-edge.tsx
  src/components/flow-builder/hooks/useDeleteNode.ts
  src/components/flow-builder/hooks/useEdgeClick.tsx
  src/components/flow-builder/hooks/useLayout.ts
  src/components/flow-builder/index.tsx
  src/components/flow-builder/node-types/intro-node.tsx
  src/components/flow-builder/node-types/outro-node.tsx
  src/components/flow-builder/node-types/workflow-node.tsx
  src/components/header/index.tsx
  src/components/info-card/index.tsx
  src/constants/flow-elements.tsx
  src/env.mjs
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/trpc/[trpc].ts
  src/pages/flows/[flow].tsx
  src/pages/index.tsx
  src/server/api/root.ts
  src/server/api/routers/example.ts
  src/server/api/trpc.ts
  src/server/auth.ts
  src/server/db.ts
  src/store/flow-builder.store.ts
  src/utils/api.ts
Labels: feature
